### ISSUE TITLE
Hoisted variables should evaluate to undefined but it evaluate to the later assigned value

### ISSUE THREAD

**Issue by mohamed-abdelrhman** [lukehaas/RunJS#351] opened 2021-11-03 19:30 UTC
```
console.log(message)      // Hi  should be undefined
var message;
message = "Hi"             
console.log(message)      // Hi
```
<img width="1057" alt="Screen Shot 2021-11-03 at 9 28 30 PM" src="https://user-images.githubusercontent.com/26941732/140179706-f06a771c-9b8d-48f4-939b-4d94f0adb9dc.png">

**Comment by lukehaas** [comment] 2021-11-04 09:47
@mohamed-abdelrhman thanks for raising this.

 I've taken a look and the issue is related to an experimental feature, Runtime values, which can be turned off in the advanced section of the preferences.

![Screenshot 2021-11-04 at 09 46 03](https://user-images.githubusercontent.com/741344/140292453-8c2e5bc8-907a-4686-8fc5-f2232e388b48.png)

I'd suggest disabling this for now and I'll aim to have this fixed in the next release.

**Closed** 2021-11-04 09:59 UTC
