### ISSUE TITLE
Can use it only with FullScreen

### ISSUE THREAD

**Issue by ruslanguns** [lukehaas/RunJS#440] opened 2022-06-13 18:21 UTC
From one day to another, I realized that the RunJS was executing but somewhat invisible, the app is open and it's actually functioning but doesn't work like a normal window. After a while using F11 with a combination of clicking, hovering, and switching with ALT+TAB it opened on full-screen, but it still not works on normal window.

On full-screen:
![image](https://user-images.githubusercontent.com/19806968/173417939-09d17032-9e73-4275-84e9-a28e0634bc63.png)

On the taskbar:
![image](https://user-images.githubusercontent.com/19806968/173418185-61ae0f69-e529-4436-808b-d7a919f09125.png)

I tried to uninstall but maybe I need to uninstall including the cached data because it's still with the same issue.

![image](https://user-images.githubusercontent.com/19806968/173418941-23e3698c-4a73-447c-94f6-9c5ce1dbe6a4.png)

Will appreciate your help!

**Comment by lukehaas** [comment] 2022-06-13 21:11
Thanks @ruslanguns. It's not clear to me from your description what the issue is, could you explain a little more about how the window is not functioning like a normal window?

**Comment by lukehaas** [comment] 2022-06-15 15:01
@ruslanguns to investigate and resolve this issue further information is needed. What exactly is the issue you are experiencing when the app is not full screen?

**Comment by lukehaas** [comment] 2022-06-20 15:57
Closing as the issue is not clear.

**Closed by lukehaas** 2022-06-20 15:57 UTC
