### ISSUE TITLE
Bug: functions not hoisted

### ISSUE THREAD

**Issue by getify** [lukehaas/RunJS#70] opened 2019-04-06 04:54 UTC
(Possibly related to #65)

Function declarations are not hoisted as they should be:

<img width="893" alt="Screen Shot 2019-04-06 at 7 53 52 AM" src="https://user-images.githubusercontent.com/150330/55665045-306bcb00-5841-11e9-82c0-2da004d13930.png">

**Comment by lukehaas** [comment] 2019-04-11 11:51
The way RunJS works makes this a challenging problem to solve. I've experimented with ideas previously and will continue to do so. This issue will unfortunately need to be a longer term goal rather than something that can get resolved in the short term.

**Comment by getify** [comment] 2019-04-11 12:39
Understood. That's quite a bummer. :(

**Comment by mdtanrikulu** [comment] 2019-04-14 18:05
After enabling `Holistic Evaluation` from preferences > advanced, hoisting issue resolved for me.

<img width="975" alt="Screenshot 2019-04-14 at 20 02 57" src="https://user-images.githubusercontent.com/2774845/56097105-7d5e3a00-5ef0-11e9-9c63-edda67ebde5a.png">

<img width="910" alt="Screenshot 2019-04-14 at 20 03 06" src="https://user-images.githubusercontent.com/2774845/56097103-7afbe000-5ef0-11e9-995f-04e7d294cd88.png">

**Comment by getify** [comment] 2019-04-15 20:15
@mdtanrikulu Thanks, I can confirm that in fact does cause it to work. Hopefully that helps identify a solution to the bug.

**Comment by arawwad** [comment] 2019-04-25 17:15
I think this may be related to this bug
![image](https://user-images.githubusercontent.com/25812184/56754911-7526ba00-678e-11e9-8e91-0845309ff433.png)

**Comment by lukehaas** [comment] 2019-04-26 09:17
@arawwad that issue won't be related to hoisting as the function is declared first. It's likely to be some kind of syntax bug.

**Comment by getify** [comment] 2019-04-26 11:19
the function is declared in a block.

**Comment by lukehaas** [comment] 2020-11-19 17:44
@getify the hoisting problem has now been resolved 👍🥳

**Closed** 2020-12-11 12:39 UTC
Labels: bug

**Comment by chriscalo** [comment] 2021-01-15 16:39
This setting seems to have gone away: 

![image](https://user-images.githubusercontent.com/867717/104752740-0d17c480-5725-11eb-9af1-70d06f12c0b0.png)

Trying to reference a function defined "later" results in an error.

Minimal repro:

``` js
const chroma = require("chroma-js");

console.log(doThing());

function doThing() {
  return chroma;
}
```

Output:

``` text
ReferenceError: chroma is not defined
```

`chroma-js` is installed:

![image](https://user-images.githubusercontent.com/867717/104753251-b8287e00-5725-11eb-9fa6-855d625aa974.png)

And `chroma` is indeed defined, as we can see if we move the function up:

``` js
const chroma = require("chroma-js");

function doThing() {
  return chroma;
}

console.log(doThing());
```

Output:

``` text
ƒ chroma()
```

My RunJS Version is 1.12.2 (1.12.2):

![image](https://user-images.githubusercontent.com/867717/104753600-3d139780-5726-11eb-9a39-ec71b81f54c0.png)

**Comment by lukehaas** [comment] 2021-02-06 11:14
@chriscalo Holistic Evaluation has been replaced with Runtime Values, disabling Runtime Values has the same effect as enabling Holistic Evaluation.
The hoisting issue you saw was a regression that came in with version 1.12. This has been resolved in version 1.13.0.

**Comment by chriscalo** [comment] 2021-02-10 18:37
sure enough that now works for me if I turn off **show runtime values** 👍 thanks!

(not sure what I'm losing by turning that off)

**Comment by lukehaas** [comment] 2021-02-11 09:05
@chriscalo in the latest version of RunJS hoisting is working properly, with runtime values on or off.

**Comment by chriscalo** [comment] 2021-02-22 00:17
Confirmed 👍 works perfectly for me now, thanks!
