### ISSUE TITLE
SyntaxError: Label 'key' is already declared in child object

### ISSUE THREAD

**Issue by dnicolson** [lukehaas/RunJS#135] opened 2020-04-22 14:04 UTC
The issue only exists when typing the object literal, the issue does not exist when defining a variable.

<img width="1042" alt="Screen Shot 2020-04-22 at 15 58 02" src="https://user-images.githubusercontent.com/2276355/79991228-526ad680-84b2-11ea-9446-57a3991ef0ae.png">

RunJS 1.8.0

**Comment by lukehaas** [comment] 2020-04-22 14:24
This is certainly odd behavior. Thanks for raising.

**Comment by lukehaas** [comment] 2020-07-19 10:39
Having now taken a look into this, it looks like defining an unassigned object literal will cause JavaScript to interpret it as a label definition: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/label
It then complains because labels must be unique.
The same behaviour is occurring in the Chrome console:

![Screenshot 2020-07-19 at 11 34 15](https://user-images.githubusercontent.com/741344/87872875-465cbb00-c9b4-11ea-9599-c888ca9b29f8.png)

Closing this now as this seems to be the expected behaviour.

**Closed by lukehaas** 2020-07-19 10:39 UTC
Labels: bug

**Comment by dnicolson** [comment] 2020-07-19 10:54
Those blocks of code are not meant to be run together. The following code will only work in Chrome:
```
{key: {key: 'value'}}
```

The following code will work in Chrome and RunJS:
```
const object = {key: {key: 'value'}}
object;
```

**Comment by lukehaas** [comment] 2020-07-19 11:25
@dnicolson yeah, that's captured in a separate ticket: https://github.com/lukehaas/RunJS/issues/134

**Comment by dnicolson** [comment] 2020-07-19 11:29
That's a separate issue, one of the keys is quoted in #134 and the error message is different.

**Comment by lukehaas** [comment] 2020-07-19 11:36
It's fundamentally the same issue, the differing error message just depends on if the key is quoted or not.
Ultimately it's just down to JS seeing this as a label definition.

![Screenshot 2020-07-19 at 12 34 55](https://user-images.githubusercontent.com/741344/87873798-511b4e00-c9bc-11ea-9a23-9c3f14141a87.png)

![Screenshot 2020-07-19 at 12 35 07](https://user-images.githubusercontent.com/741344/87873800-54aed500-c9bc-11ea-8659-a78c77f4d0fa.png)
