### ISSUE TITLE
ElementaryOS Wingpanel bug

### ISSUE THREAD

**Issue by ohepworthbell** [lukehaas/RunJS#163] opened 2020-07-09 16:40 UTC
No icon appears for the app in ElementaryOS (as per #92) for either the app within folder view or within the Plank dock (when opened). The app also seems to not have an option to keep in the dock (right-click shows no option to pin to the dock, and when dragged into the dock to force pinning, the app persists but cannot be opened).

> Version: 1.9.0
> OS: ElementaryOS 5.1 Hera (based on Ubuntu 18.04 LTS)

A couple of other minor points: the app is a little bit slow on Linux, and it'd also be great if the title bar and menu could match the colour of the theme - currently both the title and menu bar seem to be arbitrarily coloured - see [screenshot](https://i.ibb.co/m6NvTS9/Screenshot-from-2020-07-09-17-35-13.png).

P.S. Thanks for the brilliant little app. Used it previously on my Mac, and it's great. Massively happy to see a Linux version.

**Comment by lukehaas** [comment] 2020-07-09 16:50
@ohepworthbell thanks for raising this. I'll investigate the points you've mentioned.

**Comment by z0xyz** [comment] 2020-11-14 01:26
temp solution : 

icon :
downloaded this icon from their website 
url : 
https://runjs.dev/static/icon.svg
, and then converted it to .png format with gimp 
, then made a folder / directory name "runjs" at 
$HOME/.local/share
, and saved the new png at this folder 

, created a " runjs.desktop  " file at 

 /home/usr/.local/share/applications

content : 

[Desktop Entry]
Encoding=UTF-8
Version=1.12.2
Type=Application
Name=runJS
GenericName=javascript playground
Icon=/home/usr/.local/share/runjs/icon.png
Exec=/usr/bin/runjs
Categories=Development;

in the content of the file here the Icon & Exec path is relative to yours 


my OS : elementary OS 5.1.7

**Comment by lukehaas** [comment] 2023-04-19 14:23
@ohepworthbell are you still seeing this issue?

**Comment by ohepworthbell** [comment] 2023-04-19 14:29
Unfortunately I am no longer using ElementaryOS so cannot confirm if the issue still exists

**Comment by lukehaas** [comment] 2023-04-19 14:58
Gonna close this as the issue is likely upstream if it still exists.

**Closed by lukehaas** 2023-04-19 14:58 UTC
Labels: bug
