### ISSUE TITLE
setInterval keeps running

### ISSUE THREAD

**Issue by devism** [lukehaas/runjs#26] opened 2019-01-09 06:53 UTC
The following code keeps executing even after removal. Only way to stop it is to quit the app. 

```
setInterval(function(){
  console.log('yo');
}, 2000)
```

**Comment by multics** [comment] 2019-01-09 15:14
I believe it is because `node` is running under the hood. Even the code is removed, the timer you started won't stop, unless you do `clearInterval`.

Same reason, if you do `process.argv`, you will see all the arguments of the app.
And if you do `process.exit(-1)`, the app won't work properly any more.

All these cases need to be handled unless it is intended behavior.

**Comment by lukehaas** [comment] 2019-02-09 16:27
@devism This is now resolved in version 1.2.4

@multics The cases you described regarding `process` are also now resolved 1.2.4

**Closed** 2019-02-15 17:13 UTC
Labels: bug
